apiVersion: v1
kind: Service
metadata:
  name: spark-app-exporter
  namespace: default
  labels:
    app: spark-app-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9300
    targetPort: 9300
    name: metrics
  selector:
    app: spark-app-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-app-exporter
  namespace: default
  labels:
    app: spark-app-exporter
spec:
  selector:
    matchLabels:
      app: spark-app-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
